HotelBookingApp.WEB/Controllers/PersonalOfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using HotelBookingApp.BLL.Interfaces;
using HotelBookingApp.WEB.Models;

namespace HotelBookingApp.WEB.Controllers
{
    [Authorize]
    public class PersonalOfficeController : Controller
    {
        IBookingService bookingService;

        public PersonalOfficeController(IBookingService service)
        {
            bookingService = service;
        }

        public ActionResult Index()
        {
            var alerts = bookingService.GetUserUnpaidBills(User.Identity.GetUserId()).Count;
            ViewBag.Alerts = alerts;

            return View();
        }

        public ActionResult Alerts()
        {
            var bills = bookingService.GetUserUnpaidBills(User.Identity.GetUserId());
            var bookings = bookingService.GetUserBookings(User.Identity.GetUserId());
            List<BookingViewModel> userBookings = new List<BookingViewModel>();

            foreach (var b in bills)
            {
                var currentBooking = bookings.Find(booking => booking.BillId == b.Id);

                if (!currentBooking.IsCanceled)
                {
                    userBookings.Add(new BookingViewModel
                    {
                        Id = currentBooking.Id,
                        BillId = b.Id,
                        BookingDate = currentBooking.BookingDate,
                        DateOfArrival = currentBooking.DateOfArrival,
                        DaysOfArrival = currentBooking.DaysOfArrival,
                        Price = b.Price
                    });
                }
            }

            return View(userBookings);
        }
    }
}

HotelBookingApp.WEB/Areas/Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel booking", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" },null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Personal office", "Index", "PersonalOffice", new { area = "" }, null)</li>
                    }
                    @if (User.IsInRole("Moderator") || User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Moderator page", "Index", "Home", new { area = "Manager" }, null)</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin page", "Index", "Home", new { area = "Admin" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Rybitskiy A.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>